sudo: required

services:
  - docker

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - ls -lah
  - docker build -t goodjob/postgres-fdw .

after_success:
  - curl -X POST -H 'Content-Type: application/json' -d {"branch":"$TRAVIS_BRANCH"} https://githook.gj.kr0.fr"
