sudo: required

services:
  - docker

script:
  - docker build -t goodjob/postgres-fdw:base -f Dockerfile.base .
  - docker build -t goodjob/postgres-fdw:oracle -f Dockerfile.oracle .

after_success:
  - bash deploy.sh
