sudo: required

services:
  - docker

before_install:
 - ls || curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - ls || chmod +x docker-compose
 - ls || sudo mv docker-compose /usr/local/bin

script:
  - ls -lah
  - ls || docker build -t goodjob/postgres-fdw .

after_success:
  "curl https://githook.gj.kr0.fr?branch=$TRAVIS_BRANCH"
